import sys

# Build the correct app.py line by line to avoid escaping nightmares
lines = []

lines.append('"""SharpSplat - SHARP 3D Gaussian Splatting 图形化管理工具"""\n')
lines.append('\n')
lines.append('from __future__ import annotations\n')
lines.append('\n')
lines.append('import logging\n')
lines.append('import shutil\n')
lines.append('import subprocess\n')
lines.append('from pathlib import Path\n')
lines.append('\n')
lines.append('import gradio as gr\n')
lines.append('from fastapi.responses import FileResponse\n')
lines.append('\n')
lines.append('logging.basicConfig(level=logging.INFO)\n')
lines.append('logger = logging.getLogger(__name__)\n')
lines.append('\n')
lines.append('BASE_DIR = Path(__file__).resolve().parent.parent.parent\n')
lines.append('OUTPUTS_DIR = BASE_DIR / "outputs"\n')
lines.append('UPLOADS_DIR = BASE_DIR / "uploads"\n')
lines.append('VIEWER_DIR = BASE_DIR / "viewer"\n')
lines.append('ML_SHARP_DIR = BASE_DIR / "ml-sharp"\n')
lines.append('\n')
lines.append('for d in [OUTPUTS_DIR, UPLOADS_DIR]:\n')
lines.append('    d.mkdir(exist_ok=True)\n')
lines.append('\n')
lines.append('\n')
lines.append('def run_sharp_predict(\n')
lines.append('    image_paths: list[str],\n')
lines.append('    progress: gr.Progress = gr.Progress(),\n')
lines.append(') -> tuple[list[dict], str]:\n')
lines.append('    results = []\n')
lines.append('    for i, src in enumerate(progress.tqdm(image_paths)):\n')
lines.append('        src_path = Path(src)\n')
lines.append('        stem = src_path.stem\n')
lines.append('        dest = UPLOADS_DIR / src_path.name\n')
lines.append('        shutil.copy2(src_path, dest)\n')
lines.append('        try:\n')

with open("src/sharpsplat/app.py", "w", encoding="utf-8") as f:
    f.writelines(lines)
